compiler: Compiler error when Link is set and Tooltip is an URL
terrastruct/d2 pull request #1091
Opened 2023-03-26 17:04 UTC by alankan886

2023-03-26 17:10 UTC, alankan886 commented
Some `.svg`, `.png` and `.pdf` files were "update" (although it looks the same) after I ran `./make.sh`, let me know if that's not expected. Also if the new tests I added are preferred in a different test file, lmk as well!

2023-03-27 03:35 UTC, alixander requested changes
@alankan886 thank you! 🚀 

The differing unrelated tests are due to computer architecture. I bet you're on x64 intel or some other AMD machine. These tests were generated on our ARM machines. Why is there a difference? TBD! https://github.com/terrastruct/d2/issues/921

In the meantime, could you uncheck these from Git? Sorry for the trouble.

Lastly, could you sign your commits please? https://github.com/terrastruct/d2/blob/master/docs/CONTRIBUTING.md#logistics

2023-03-27 03:35 UTC, alixander commented on ci/release/changelogs/next.md
> +- prevent `tooltip` to be an URL when `link` is already set. [#888](https://github.com/terrastruct/d2/pull/1091)
number is not right

2023-03-27 03:35 UTC, alixander commented on d2compiler/compile.go
> +			c.errorf(scalar, "Tooltip cannot be an URL when Link is set")
"Tooltip cannot be set to URL when link is also set (for security)"

2023-03-27 03:35 UTC, alixander commented on d2compiler/compile_test.go
> +		{
good set of tests!

2023-03-27 03:37 UTC, alixander commented on ci/release/changelogs/next.md
> +- prevent `tooltip` to be an URL when `link` is already set. [#888](https://github.com/terrastruct/d2/pull/1091)
oh i see, you used the issue number and linked the PR. they should be the same number though, choose whichever one has more context

2023-03-27 23:19 UTC, alankan886 commented
Thanks for the quick review! I made the changes based on the comments, lmk if it's good!

2023-03-27 23:39 UTC, alixander requested changes
<img width="969" alt="Screen Shot 2023-03-27 at 4 38 55 PM" src="https://user-images.githubusercontent.com/3120367/228090652-f098948c-8440-4424-94a8-5f5be5f5c8a7.png">

@alankan886 can you squash your commits so that there's only the verified one? looks good other than that!

2023-03-28 01:40 UTC, alankan886 commented
One second, looks like the unwanted changes are back again.

2023-03-28 04:26 UTC, alixander approved these changes
thanks @alankan886 !

2023-03-28 04:27 UTC, merged

2023-03-28 04:30 UTC, alankan886 commented
@alixander oh nooooo I was about to squash again, I was struggling a bit because I was so used to using squash and merge on Github rip

2023-03-28 04:34 UTC, alixander commented
hah appreciate that @alankan886 but no big deal =). it's a good point though i suppose i should wait for confirmation from the author after approving and before merging. will do next time.

and welcome to the community!