GH 821: links on pptx
terrastruct/d2 pull request #1168
Opened 2023-04-09 23:30 UTC by ejulio-ts

This is a WiP.
Currently it works with PowerPoint, but links aren't showing up on KeyNote (probably some missing tag or something similar)..

2023-04-10 22:05 UTC, alixander requested changes
is there a way to show mouse cursor for external links?

other than these small things, looks good to go

2023-04-11 01:01 UTC, gavin-ts commented
as another issue, I wonder if the appendix should take in a root name so `1: root > mobile` matches the slide title `out / mobile` based on filename `out`?

2023-04-11 13:22 UTC, ejulio-ts commented
> as another issue, I wonder if the appendix should take in a root name so 1: root > mobile matches the slide title out / mobile based on filename out?

That's something I was thinking too. Another alternative is to not name the board based on the output file and use `root`

2023-04-11 13:32 UTC, ejulio-ts commented
@alixander what do you mean here

> is there a way to show mouse cursor for external links?

Keep the standard cursor instead of pointer for external links?

2023-04-11 14:11 UTC, alixander commented
<img width="804" alt="Screen Shot 2023-04-11 at 7 11 19 AM" src="https://user-images.githubusercontent.com/3120367/231190192-fa20d43d-ae87-423a-a5b2-21436c27d8c4.png">

no i want all links to be cursor pointer. here, the mouse doesn't switch to cursor pointer?

2023-04-11 15:59 UTC, ejulio-ts commented
It seems to be a bug in PowerPoint. When I click on a slide link and then move the mouse over another link, it loses the pointer. I need to click again to get it back.

https://user-images.githubusercontent.com/102628724/231221021-0aa359a8-5c97-48a7-8737-cb53a229676e.mp4

2023-04-11 16:30 UTC, alixander approved these changes

2023-04-11 16:30 UTC, alixander commented on lib/png/png.go
> +const SCALE = 2.
use it in `png` too

2023-04-11 17:54 UTC, merged