chore: fixing typos
terrastruct/d2 pull request #1193
Opened 2023-04-13 17:23 UTC by deining

The [go report card](https://goreportcard.com/report/oss.terrastruct.com/d2) for this project complains about misspellings in this project. This PR corrects this and fixes a few other typos on the way.

2023-04-13 17:38 UTC, gavin-ts commented on ci/release/changelogs/v0.1.0.md
> +- LaTex is now supported. See [docs](https://d2lang.com/tour/text) for how to use. [#229](https://github.com/terrastruct/d2/pull/229)
```suggestion
- LaTeX is now supported. See [docs](https://d2lang.com/tour/text) for how to use. [#229](https://github.com/terrastruct/d2/pull/229)
```

2023-04-13 20:24 UTC, gavin-ts approved these changes

2023-04-13 20:28 UTC, alixander requested changes
ah, would u mind signing your commits please? same with the docs PR

2023-04-14 05:50 UTC, deining commented
> ah, would u mind signing your commits please?

Thanks for reminding, the commit is signed now.
Note: as a minor amendment, I bumped versions of the GitHub workflow files.

2023-04-14 18:48 UTC, alixander approved these changes

2023-04-14 18:49 UTC, merged