themes: add dark terrastruct flagship theme
terrastruct/d2 pull request #1194
Opened 2023-04-13 18:10 UTC by berniexie

Closes #1150 

![demo](https://user-images.githubusercontent.com/6413609/231847031-e59ed227-eb64-4a2f-8cca-380c98545e13.svg)

2023-04-13 18:21 UTC, alixander requested changes
add an example in themes_test (https://github.com/alixander/d2/blob/master/e2etests/themes_test.go)

2023-04-13 21:44 UTC, alixander reviewed
Let's keep dark themes in the same band of IDs. https://github.com/terrastruct/d2/blob/cce35e5d051664fd4765062430c0ff5b26b105b9/d2themes/d2themes.go#L25

2023-04-13 21:44 UTC, alixander commented on ci/release/changelogs/next.md
> +- Fixes an issue where PNG exports that were too large were crashing [#1093](https://github.com/terrastruct/d2/issues/1093)
this is wrong pr

2023-04-13 22:21 UTC, berniexie commented on ci/release/changelogs/next.md
> +- Fixes an issue where PNG exports that were too large were crashing [#1093](https://github.com/terrastruct/d2/issues/1093)
oh well, gotta include it now

2023-04-13 22:34 UTC, alixander requested changes

2023-04-13 22:34 UTC, alixander commented on ci/release/changelogs/next.md
> +- New dark theme "Dark Terrastruct Flagship" with the theme ID of `2` [#1150](https://github.com/terrastruct/d2/issues/1150)
id

2023-04-14 00:14 UTC, alixander approved these changes

2023-04-14 01:58 UTC, merged