readme: update
terrastruct/d2 pull request #143
Opened 2022-11-22 17:21 UTC by alixander

closes #141

fine fine fine

2022-11-22 17:30 UTC, nhooyr requested changes

2022-11-22 17:30 UTC, nhooyr commented on README.md
> +> This is syntax highlighted with editor plugins.
```suggestion
> There is syntax highlighting with the editor plugins linked below.
```

2022-11-22 17:33 UTC, nhooyr approved these changes

2022-11-22 17:36 UTC, merged

2023-09-04 17:56 UTC, XoL1507 commented
para saan to?