layout: Orientation keyword
terrastruct/d2 pull request #251
Opened 2022-11-29 05:45 UTC by alixander

Specify `horizontal` or `vertical`.

dagre and ELK both only support a single top-level orientation. We can support multiple orientation of different containers in TALA.

Dagre makes this clear in their docs that it's just a top level setting.
There's a few issues asking this from ELK: https://github.com/kieler/elkjs/issues/26

It's apparently possible in Graphviz, but you have to finangle the fuck out of it with invisible nodes and edges and customize every graph: https://stackoverflow.com/questions/7777722/top-down-subgraphs-left-right-inside-subgraphs .

2022-11-29 06:28 UTC, nhooyr reviewed
should we instead support values like `up-down`, `down-up`, `left-right` and `right-left`?

2022-11-29 06:28 UTC, nhooyr commented on d2compiler/compile_test.go
> +				diff.AssertStringEq(t, "vertical", g.Objects[0].Attributes.Orientation.Value)
why is this vertical but root above is horizontal by default?

2022-11-29 06:32 UTC, alixander commented
> should we instead support values like up-down, down-up, left-right and right-left?

oh interesting, for right-to-left languages like japanese/chinese, i can see that. maybe it should just be called direction then

2022-11-29 06:33 UTC, alixander commented
nvm, direction feels like it should be a property from node to another node. for a property on a parent controlling its children, orientation still sounds more right

2022-11-29 06:46 UTC, nhooyr commented on d2compiler/compile_test.go
> +				diff.AssertStringEq(t, "vertical", g.Objects[0].Attributes.Orientation.Value)
lol my b

2022-11-29 06:47 UTC, nhooyr commented
I prefer direction now, I think it matches the constants better. I don't share your concern.

2022-11-29 06:53 UTC, alixander commented
ok good to know, maybe just me then. as mentioned, +1 to direction being a slightly simpler vocab than orientation

2022-11-30 00:35 UTC, nhooyr requested changes

2022-11-30 00:35 UTC, nhooyr commented on e2etests/stable_test.go
> +	1 -> 2 -> 3 -> 4 -> 5
indent

2022-11-30 00:45 UTC, nhooyr approved these changes

2022-11-30 00:52 UTC, merged