layout: sequence diagrams
terrastruct/d2 pull request #317
Opened 2022-12-01 22:39 UTC by ejulio-ts

fixes #99 

I'll followup with a PR to docs showcasing this.

Before any layout engine runs, sequence diagrams are processed.
Their content is replaced with a rectangle, of the same size of the laid out diagram, and then the layout engine just needs to place this object.
Later, the sequence diagram is moved around and added back to the graph.

Sequence diagram edges (messages) are also removed from the graph.

Renamed `edges`, in sequence diagrams, to `messages` as it is the definition in UML.

Added e2e test cases

2022-12-01 23:03 UTC, alixander requested changes
let's see some TALA runs

2022-12-01 23:03 UTC, alixander commented on d2layouts/d2sequence/layout.go
> +// Layout identifies and layouts sequence diagrams within a graph
performs layout on

2022-12-02 00:40 UTC, alixander requested changes
i don't think we should wrap to compose layout engines. i think just simple in-order run-through is best. what if we implement swimlanes then gantt, etc? starts to get into 4 nested funcs.

or like, maybe we can let users specify a different layout for each container.

how about we change the signature of a layout to be `func(ctx, g) (cleanup, err)`, and then for the core layouts, the cleanup is just a no-op.

then u can have a function that runs multiple

```
func RunLayouts() (err error) {
	layouts := [d2sequence.Layout, layout]
	for _, layout := range layouts {
		cleanup, err := layout(ctx, g)
		if err != nil { return err }
		defer func() { 
			if err != nil {
				err = cleanup()
			}
		}
	}
        return nil
}
```

2022-12-02 00:45 UTC, ejulio-ts commented
I don't see any issue with nesting and composition, that's the whole deal with making things extensible. If these calls were recursive, then I'd say it could become an issue
I just went with a simple `decorator` approach here. If you think that it needs to change the API, then ok..

Just note that your particular example leaves cleanup to the end of everything, while you might want to restore things on the go..

2022-12-02 00:46 UTC, alixander commented
wdym "restore things on the go"? at no point would one layout engine want to do anything before another layout has finished right?

2022-12-02 00:48 UTC, alixander commented
> that's the whole deal with making things extensible

i also don't get why it's "the whole deal with making things extensible". there's many different ways

>  leaves cleanup to the end of everything,

not of everything, just... until another layout engine finished

2022-12-02 01:08 UTC, ejulio-ts commented
> wdym "restore things on the go"? at no point would one layout engine want to do anything before another layout has finished right?

In your example, you defer `cleanup` and, as I understand, it only runs when `RunLayouts` ends. In this case, the layouts would only cleanup and restore the state after everything ran.
I get your idea, I see no problem with as I see no problem with this one.
The only thing with yours is that for `cleanup` you'll need either an object to store the state or create a closure to keep the state around.
While in function composition, just pass a single pointer around and the "closure" is kept by the call stack. I also get that the current function interface is not proper for this as `d2sequence` exposes a different interface than the plugins.

2022-12-02 01:12 UTC, alixander commented
> after everything ran.

isn't that the same as right now? your cleanup code only runs after dagre is run. 

> exposes a different interface than the plugins.

yes we would need a different interface. i'm okay doing this in another PR and we leave structure as is for this one

2022-12-02 03:53 UTC, alixander requested changes
the sequence_diagram code is nice and clean, but i think the layout code needs some work. i think a bunch of these data structures are unnecessary or can be simplified

2022-12-02 03:53 UTC, alixander commented on d2layouts/d2sequence/layout.go
> +			sdMock := obj.EnsureChild([]string{"sequence_diagram"})
oh interesting, a new object as a child of the sequence diagram...

2022-12-02 03:53 UTC, alixander commented on d2layouts/d2sequence/sequence_diagram.go
> +func (sd *sequenceDiagram) isActor(obj *d2graph.Object) bool {
save the root object on the sequenceDiagram. Then, if the obj.parent == the root object, then u know it's an actor

2022-12-02 19:56 UTC, alixander approved these changes

2022-12-02 21:03 UTC, merged