sequence diagram: self edges
terrastruct/d2 pull request #336
Opened 2022-12-03 18:03 UTC by ejulio-ts

based on https://github.com/terrastruct/d2/pull/273
routes self edges and edges to descendants
added a new test case (shown below)
![_Users_juliobatista_Projects_terrastruct_d2_sequence svg (8)](https://user-images.githubusercontent.com/102628724/205455156-c43687bb-4473-4828-a54a-8352dfb4a3ad.png)

2022-12-03 18:15 UTC, alixander commented
<img width="541" alt="Screen Shot 2022-12-03 at 10 08 43 AM" src="https://user-images.githubusercontent.com/3120367/205455658-249f06e0-60a0-4a24-8c35-d6dd7e462ae9.png">

@katwangy what do u think? should we have labels in middle or up top like sequencediagram.org does? i think on top to get more space.

@ejulio-ts ur PRs need to always either include test case (we have a todo_test.go specifically for these) or add a note or address it somehow. "a deeper descendant" looks like it's about to overflow, so if u make it longer, does it? or do u handle it?

2022-12-04 04:14 UTC, ejulio-ts commented
![_Users_juliobatista_Projects_terrastruct_d2_sequence svg (9)](https://user-images.githubusercontent.com/102628724/205474115-7652a279-2889-483b-87dd-9e636c4f1fbe.png)

something like this, @alixander ?

2022-12-04 04:44 UTC, alixander commented
yes. i think u should place these labels like sequencediagram.org does -- on top

2022-12-04 17:28 UTC, alixander requested changes

2022-12-04 17:28 UTC, alixander commented on d2layouts/d2sequence/sequence_diagram.go
> +			// rankDiff = 0 for self edges
self edges need extra padding too. for long self-edge labels.

2022-12-04 17:28 UTC, alixander commented on d2layouts/d2sequence/sequence_diagram.go
> +	endY := lastRoute[len(lastRoute)-1].Y + MIN_MESSAGE_DISTANCE
u need to for loop the route, prepare for non-instantaneous msgs

2022-12-04 17:29 UTC, alixander commented
we can get the edge label in another PR, good to just have the ability to do self edges for now

2022-12-05 03:42 UTC, merged