fmt: Preserve leading comment spacing
terrastruct/d2 pull request #402
Opened 2022-12-07 16:30 UTC by alixander

fixes #400

2022-12-08 02:46 UTC, nhooyr requested changes

2022-12-12 19:58 UTC, pleshevskiy commented on d2format/format.go
> -		if line != "" && !strings.HasPrefix(line, " ") {
I confirm that this PR fixes the issue.

As an input to this function, strings with comments without # and one space go into this function. By removing this check, we always add one space in its place.

2022-12-13 10:46 UTC, nhooyr commented on d2format/format.go
> -		if line != "" && !strings.HasPrefix(line, " ") {
Ah right that makes sense, as otherwise when we parse again the leading space isn't parsed as part of the comment.

2022-12-13 10:46 UTC, nhooyr approved these changes
Thanks @pleshevskiy

2022-12-13 18:09 UTC, alixander commented on d2format/format.go
> -		if line != "" && !strings.HasPrefix(line, " ") {
> This is supposed to just add a leading space to comments without leading spaces.

i added a test case for this: https://github.com/terrastruct/d2/pull/402/files#diff-f5d6f3315c026ce320a9cb3a4e2b86eb851bf4e3ddb65a2607bf996f8ab04409R603

2022-12-13 18:09 UTC, merged