Implement the `double_circle` shape including basic shape and the sketch.
terrastruct/d2 pull request #565
Opened 2022-12-30 09:33 UTC by OneRain233

Implement the `double_circle` shape including basic shape and the sketch.
#564

2022-12-30 10:48 UTC, pleshevskiy commented on lib/shape/shape.go
> +//	▼
You broke the ascii diagram :)

2022-12-30 13:04 UTC, ejulio-ts commented
@OneRain233 can you include an image of your change? Quite hard to guess what it is from changes :)

Also, can you update this test case https://github.com/terrastruct/d2/blob/master/e2etests/stable_test.go#L26?

2022-12-30 13:36 UTC, OneRain233 commented
For the `all_shape` test, I found that the size of the double circle shape is larger than others. But when I ran the normal `.2d` file, it is normal. I dont know the reason.
```
x1:{shape:double_circle}
x2:{shape:circle}
x1 -> x2
```
![Screenshot from 2022-12-30 21-35-31](https://user-images.githubusercontent.com/73395917/210075926-3088922d-fc15-4e27-8319-b4723a1f5a3c.png)


![test](https://user-images.githubusercontent.com/73395917/210075768-c6585565-b40a-4401-aec6-98fdc032a265.svg)

2022-12-30 13:51 UTC, pleshevskiy commented
@OneRain233 The shape stretches from the label size. I think you can make a little less internal padding

2022-12-30 13:54 UTC, OneRain233 commented
> @OneRain233 The shape stretches from the label size. ~I think you can make a little less internal padding~

Maybe I know the reasons, because the name `double_circle` is longer than others name.

2022-12-30 17:29 UTC, ejulio-ts reviewed
cool!
Besides updating the test cases, you need to update their output too
```
TESTDATA_ACCEPT=1 ./ci/test.sh
```
and it'll update the SVGs and JSONs of the test cases, otherwise it'll break during the CI run


I'll let @alixander or @nhooyr make the final call on this one.

2022-12-30 17:29 UTC, ejulio-ts commented on d2renderers/d2sketch/sketch.go
> +	js_big_circle := fmt.Sprintf(`node = rc.ellipse(%d, %d, %d, %d, {
go styling is `camelCase` and not `snake_case`

2022-12-30 17:29 UTC, ejulio-ts commented on d2renderers/d2svg/d2svg.go
> +	return fmt.Sprintf(`<ellipse class="shape" cx="%f" cy="%f" rx="%f" ry="%f" style="%s" />
you can call `renderOval` twice here.
another alternative is to remove this function and call `renderOval` twice in the main one

2022-12-30 17:50 UTC, alixander requested changes
hi @OneRain233 thanks for taking the initiative here! 

I don't think a separate shape is right for it though. There'd no 3d_square or multiple_circle or blue_oval; these are just attributes in D2. If this were to be implemented, it should be a style like `double: true` or `double-border: true`.

I don't personally know what this double-border style is for, but I've seen it used, and, recently in this: http://www.bpmb.de/images/BPMN2_0_Poster_EN.pdf . So I do think it's good to offer this in D2. 

Btw, is there anything you felt was missing from the CONTRIBUTING.md? (did you use it at all? 😃 )

2022-12-31 06:18 UTC, OneRain233 commented
> hi @OneRain233 thanks for taking the initiative here!
> 
> I don't think a separate shape is right for it though. There'd no 3d_square or multiple_circle or blue_oval; these are just attributes in D2. If this were to be implemented, it should be a style like `double: true` or `double-border: true`.
> 
> I don't personally know what this double-border style is for, but I've seen it used, and, recently in this: http://www.bpmb.de/images/BPMN2_0_Poster_EN.pdf . So I do think it's good to offer this in D2. Oh I guess I've seen it in state machines too
> 
> Btw, is there anything you felt was missing from the CONTRIBUTING.md? (did you use it at all? smiley )

Yes, I just want to use the double circle in the accept state of state machine.

2022-12-31 06:49 UTC, alixander commented
@OneRain233 how about `double-border: true | false`? not `double`, to avoid confusion with `multiple`

2022-12-31 06:54 UTC, OneRain233 commented
> @OneRain233 how about `double-border: true | false`? not `double`, to avoid confusion with `multiple`
Yes, `double-border: true | false` is better.

2022-12-31 07:11 UTC, OneRain233 commented
Should the tag `double-border` be used only for circles or for all shapes? It may be strange for some shapes to use this tag?  @alixander

2022-12-31 07:28 UTC, OneRain233 commented
I have made `double-border` for the `circle` shape only.

2022-12-31 07:30 UTC, alixander commented
@OneRain233 I think for circles, ovals, squares, and rectangles.

2022-12-31 07:59 UTC, OneRain233 commented
![Screenshot from 2022-12-31 15-58-41](https://user-images.githubusercontent.com/73395917/210129866-0bd8442a-a898-4a32-ad31-1ee153aead86.png)
Now, it looks like this.

2023-01-18 00:38 UTC, alixander requested changes
sorry for the delay in reviewing this. it looks like all the tests changed because you ran on go 1.19. Can you run with go 1.18 please?

2023-01-18 00:38 UTC, alixander commented on d2renderers/d2svg/d2svg.go
> +	return renderOval(tl, width, height, style) + renderOval(&geo.Point{X: tl.X + 5, Y: tl.Y + 5}, width-10, height-10, style)
this should be a constant like https://github.com/terrastruct/d2/blob/bd15db4fdf77a6a1ef469489ffbee89089b83a17/d2renderers/d2svg/d2svg.go#L46

2023-01-18 00:38 UTC, alixander commented on d2renderers/d2svg/d2svg.go
> +		if !targetShape.DoubleBorder {
i'd prefer the true statement to come first in if/else

2023-01-18 00:38 UTC, alixander commented on d2renderers/d2svg/d2svg.go
> +			}
we should remove this. i don't think it'd ever look good for `multiple` + `double-border`. we just choose one at random and say it takes precedence.

2023-01-21 22:38 UTC, alixander requested changes
this turned out to look really nice, especially in sketch mode! Just a few more things:

Looks like you also need to account for when pad is 0.
`d2 --pad 0 input.d2` gave me this:
<img width="204" alt="Screen Shot 2023-01-21 at 2 32 26 PM" src="https://user-images.githubusercontent.com/3120367/213889560-9899a6ba-f53f-418e-ba3d-8fdf48b52597.png">

You can see here for example of fixing: https://github.com/terrastruct/d2/pull/685

Also just more merge conflicts with tests and changelog, sorry about that.

2023-01-21 22:38 UTC, alixander commented on d2renderers/d2svg/d2svg.go
> +var borderOffset = geo.NewVector(5, 5)
should move this to `d2target`, so it can be used both here and `d2sketch` without import cycle issues

2023-01-21 22:38 UTC, alixander commented on d2renderers/d2sketch/sketch.go
> +	});`, shape.Width-10, shape.Height-10, shape.Fill, shape.Stroke, shape.StrokeWidth, baseRoughProps)
use constant defined

2023-01-21 22:38 UTC, alixander commented on d2renderers/d2sketch/sketch.go
> +			shape.Pos.X+5, shape.Pos.Y+5, p, shapeStyle(shape),
use constant defined

2023-01-21 22:38 UTC, alixander commented on d2renderers/d2sketch/sketch.go
> +	});`, shape.Width/2, shape.Height/2, shape.Width-15, shape.Height-15, shape.Fill, shape.Stroke, shape.StrokeWidth, baseRoughProps)
why's this number different?

2023-01-21 22:38 UTC, alixander commented on d2renderers/d2svg/d2svg.go
> +						targetShape.Pos.X+15, targetShape.Pos.Y-5, targetShape.Width-10, targetShape.Height-10, style)
why 15?

2023-01-22 10:52 UTC, OneRain233 commented
> this turned out to look really nice, especially in sketch mode! Just a few more things:
> 
> Looks like you also need to account for when pad is 0. `d2 --pad 0 input.d2` gave me this: <img alt="Screen Shot 2023-01-21 at 2 32 26 PM" width="204" src="https://user-images.githubusercontent.com/3120367/213889560-9899a6ba-f53f-418e-ba3d-8fdf48b52597.png">
> 
> You can see here for example of fixing: #685
> 
> Also just more merge conflicts with tests and changelog, sorry about that.

Should I sync from the original repo and then fix the issue?

2023-01-23 11:56 UTC, ejulio-ts commented
@OneRain233, yes.
You merge/rebase the current `master` and update the tests.

2023-01-24 18:16 UTC, alixander commented
@OneRain233 looks like all the commits were pulled in

2023-01-25 12:12 UTC, OneRain233 commented
I think the issue #685 is solved. Now it looks like this.
![test](https://user-images.githubusercontent.com/73395917/214559967-6aa6277b-83b3-464d-a1b2-443375477eed.png)
![test1](https://user-images.githubusercontent.com/73395917/214560309-0b2f3e97-50a0-4757-bfa3-41a4692a18dc.png)

2023-01-25 19:17 UTC, alixander requested changes
ready to merge after 1 minor thing.

2023-01-26 02:47 UTC, alixander commented
looks like one more merge + test regeneration plz @OneRain233

2023-01-27 00:30 UTC, alixander approved these changes
we'll just merge and fix the conflict in another commit on master. Thank you @OneRain233 ! Sorry for the delays in this one

2023-01-27 00:30 UTC, merged

2023-02-10 04:13 UTC, nhooyr commented
@alixander note for the future, github normally automatically gives you write access to a contributor's branch unless the contributor has declined your access.