Add test to see if command exists with POSIX 'command'
terrastruct/d2 pull request #693
Opened 2023-01-20 01:10 UTC by exapsy

2023-01-20 01:42 UTC, nhooyr requested changes

2023-01-20 01:42 UTC, nhooyr commented on ci/e2ereport.sh
> +    if [ -x "$(command -v open)" ]; then
```suggestion
    if command -v open >/dev/null; then
```

2023-01-20 21:39 UTC, nhooyr requested changes

2023-01-20 21:39 UTC, nhooyr commented on ci/e2ereport.sh
> +    elif [ -x "$(command -v xdg-open)" ]; then
this one too please!

2023-01-21 17:01 UTC, exapsy commented on ci/e2ereport.sh
> +    elif [ -x "$(command -v xdg-open)" ]; then
Done!

2023-01-22 00:22 UTC, nhooyr requested changes

2023-01-22 00:22 UTC, nhooyr commented on ci/e2ereport.sh
> +    elif [ -x "$(command -v xdg-open >/dev/null)" ]; then
```suggestion
    elif command -v xdg-open >/dev/null; then
```

2023-01-23 02:14 UTC, nhooyr requested changes
apologise for all the little change requests haha

2023-01-23 02:14 UTC, nhooyr commented on ci/e2ereport.sh
> +      open $REPORT_OUTPUT
```suggestion
      open "$REPORT_OUTPUT"
```

2023-01-23 02:14 UTC, nhooyr commented on ci/e2ereport.sh
> +      xdg-open $REPORT_OUTPUT
```suggestion
      xdg-open "$REPORT_OUTPUT"
```

2023-02-10 04:10 UTC, nhooyr commented
Thank you @exapsy 🚀

2023-02-10 08:43 UTC, alixander commented
looks like you still have to approve @nhooyr

2023-02-10 08:47 UTC, nhooyr approved these changes
✅

2023-02-10 08:47 UTC, merged