Add option for fit to screen
terrastruct/d2 pull request #721
Opened 2023-01-26 02:34 UTC by bluemir

Add CLI option for disable `fit to screen` script. ( `--disable-fit-to-screen` )

It might be solution for this issue https://github.com/terrastruct/d2/issues/659#issue-1532664265

Test failed when I run `./ci/test.sh` in my laptop, but it looks like not related to this change. 
(I have no idea to fix it)

2023-01-26 19:03 UTC, gavin-ts reviewed
this looks good to me but I wonder if we should have it inverted (`--fit-to-screen` / `--fit`) to enable as mentioned in #659. related discussion https://github.com/terrastruct/d2/pull/601#discussion_r1060938685 
I also wonder if we could do the fitting with just css instead of js

2023-01-30 15:38 UTC, bluemir commented
I think the '--fit-to-screen' option is better, too. 
so I change it.

2023-01-30 21:25 UTC, gavin-ts approved these changes

2023-01-31 01:11 UTC, gavin-ts commented
Since the default behavior no longer adds the js, the test svgs need to be updated with `TESTDATA_ACCEPT=1 ./ci/test.sh`

2023-02-01 01:40 UTC, alixander commented
hold off on this for a sec, need to think about this whole fit to screen thing

2023-02-25 16:36 UTC, alixander commented
now that the resizing is done with CSS, i wonder if anyone would still want to turn this off. i'll leave this up for a little longer to wait and see, but i suspect that https://github.com/terrastruct/d2/pull/725 solves all resizing woes.

2023-03-23 00:15 UTC, gavin-ts commented
#1080

2023-03-23 00:18 UTC, alixander commented
hey @bluemir sorry for the looong delay. had to see if anyone was still interested in this after a bunch of fixes. https://github.com/terrastruct/d2/issues/1080 is motivating enough. do you still have interest in making this change? if so, perhaps it'd be easier to just start a new PR given all the merge conflicts.

2023-03-23 03:05 UTC, gavin-ts requested changes

2023-03-23 03:05 UTC, gavin-ts commented on d2renderers/d2svg/d2svg.go
> +	}
I think this should be the same as `setDimensions` above now. setting dimensions disables the fit to screen behavior.

2023-03-23 03:09 UTC, gavin-ts commented on d2renderers/d2svg/d2svg.go
> +	}
I think we also want to rename the option to  `--no-fit` or `--sized` since we want the fit behavior as default now

2023-03-23 17:25 UTC, gavin-ts commented on d2cli/main.go
> +		NoFit:         noFit,
Since NoFit does the same thing as `SetDimensions`, I think it is better to just have `SetDimensions: toPNG || noFit,` without another RenderOpt

2023-03-24 04:12 UTC, pangloss commented on d2renderers/d2svg/d2svg.go
>  	}
I experimented with applying this change in a diagram and learned that it does not do what I expected. Please see the note here: https://github.com/terrastruct/d2/issues/1080#issuecomment-1482221132

2023-04-06 18:24 UTC, gavin-ts commented on d2cli/watch.go
> +		svg, _, err := compile(ctx, w.ms, w.layoutPlugin, w.sketch, w.center, w.pad, w.themeID, w.darkThemeID, w.inputPath, w.outputPath, w.bundle, w.forceAppendix, w.noFit, w.pw.Page)
if we want this to affect watch mode we will need to update the js code, but that should be a follow up PR that addresses #1080.

2023-04-07 00:17 UTC, alixander requested changes
@bluemir if you want to fix the merge conflicts, we can get this merged, thank you!

2023-11-07 18:39 UTC, closed without merging