todo: panic with steps
terrastruct/d2 pull request #783
Opened 2023-02-09 23:06 UTC by alixander

just added the panicking test

2023-02-09 23:29 UTC, nhooyr approved these changes
oh yes definitely should not should be an error. I guess somewhere I'm assuming each child of a steps is a map.

2023-02-22 21:45 UTC, alixander commented
> I guess somewhere I'm assuming each child of a steps is a map.

your hunch is correct

2023-02-22 22:28 UTC, nhooyr requested changes

2023-02-22 22:28 UTC, nhooyr commented on d2ir/compile.go
> +			if steps.Fields[i-1].Map() == nil {
Check if there's a scalar/array too and if so, error.

2023-02-22 22:45 UTC, nhooyr requested changes

2023-02-22 22:45 UTC, nhooyr commented on d2ir/compile.go
> +			if steps.Fields[i-1].Map() == nil {
None of the compiler functions return an error. You use `c.errorf()` to report it and skip the offending section.

2023-02-22 22:45 UTC, nhooyr commented on d2ir/compile.go
> +			if steps.Fields[i-1].Map() == nil {
my main point though is that a step *must* be either a map or not set to any value.

2023-02-23 00:01 UTC, nhooyr commented on d2ir/compile.go
> +			if steps.Fields[i-1].Map() == nil || steps.Fields[i-1].Primary() != nil {
Remove this and break above instead. This error isn't accurate anyway and reports the wrong step as being invalid.

2023-02-23 00:23 UTC, nhooyr approved these changes
✅

2023-02-23 00:27 UTC, merged