build: `make` bails on the wrong go version
terrastruct/d2 pull request #951
Opened 2023-03-01 18:50 UTC by wycats

This code:

1. Extracts the required go minor from `go.mod`
2. Gets the current go version from `go version` and normalizes it
3. Checks whether the required go minor is a version prefix for the current go
version, and bails if it isn't.

The conditional is more complicated than it would be if this script supported bash extensions to the POSIX shell standard, but changing to `#!/bin/bash` seemed out of scope for this change.

2023-03-01 18:55 UTC, nhooyr requested changes
I appreciate the shellfu but we don't need all that. Just error if `if ! go version | grep -q 1.18`.

And do it below `cd -- "$(dirname "$0")"`.

And instead of using printf, use `printferr` which is sourced in this script. It works just like `printf`.

2023-03-01 20:12 UTC, wycats commented
> I appreciate the shellfu but we don't need all that. Just error if `if ! go version | grep -qF 1.18`.

It seems useful to leave in the code that gets the version out of `go.mod`, right? Otherwise we end up with two sources of truth that have to be kept in sync.

2023-03-01 20:37 UTC, wycats commented
>

2023-03-01 20:57 UTC, nhooyr commented
> It seems useful to leave in the code that gets the version out of go.mod, right? Otherwise we end up with two sources of truth that have to be kept in sync.

They don't need to be kept in sync because they don't mean the same thing. The `go.mod` version is the earliest version that our code compiles on. This check is for CI where newer go versions screw up our code formatting.

2023-03-01 20:58 UTC, nhooyr requested changes

2023-03-01 21:46 UTC, nhooyr commented
It's also not something we're going to bump. As soon as we can build on Go 1.19, the restriction will be removed.

2023-03-02 18:39 UTC, wycats commented on make.sh
> +GO_VERSION=$(sed -En 's/^go[[:space:]]+([[:digit:].]+)$/\1/p' go.mod)
okey dokey!

2023-03-02 19:08 UTC, nhooyr requested changes

2023-03-02 19:08 UTC, nhooyr commented on make.sh
> +if ! $(go version | grep -qF "1.18."); then
```suggestion
if ! go version | grep -qF '1.18'; then
```

2023-03-02 19:08 UTC, nhooyr commented on make.sh
> +  printferr "You need go 1.18 to build d2.\n"
```suggestion
  echoerr "You need go 1.18 to build d2."
```
Just realized you don't need printf anymore.

2023-03-03 16:17 UTC, nhooyr approved these changes
nice ✅

2023-03-03 17:22 UTC, alixander commented
thank you @wycats ! (tbh i originally thought matching with go.mod was right too, appreciate the forethought anyway)

2023-03-03 17:23 UTC, merged